#!/usr/bin/env bash
#Install nginx web server

sudo apt-get -y update
#installing nginx
sudo apt-get -y install nginx
#starting nginx
sudo service nginx start
#allowing nginx through the firewall
sudo ufw allow 'Nginx HTTP'
#give permission to the user to edit the default directory
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www/html

echo "Hello World!" | sudo tee /var/www/html/default/index.html
sudo service nginx restart
echo "Nginx has been installed and started. You can access it by going to your browser and typing in the IP address of the server." 