#!/usr/bin/env bash
# Configuring web-01 to have HTTP response header

# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing redirections
new_string = "server_name _;\n\trewrite ^ https://www.google.com/ permanent;"

sudo sed -i "s/server_name _;/$new_string/g" /etc/nginx/sites-available/default

# creating custom error page
echo " It's a 404 error page" | sudo tee /usr/share/nginx/html/404.html

# custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Test for syntax errors
sudo nginx -t

# Restarting nginx
sudo service nginx restart