#!/usr/bin/env/bash
# Server-01 login commands

# Setting up the SSH-agent
eval $("ssh-agent -s")

# Path to identifyFile
ssh-add /home/clencyc/.ssh/id_rsa

# Username and IP Address
ssh ubuntu@54.175.136.113